### ISSUE TITLE
Docs for admins

### ISSUE THREAD

**Issue by DarkCat09** [TxtDot/documentation#1]
Installation and configuration docs for admins.

**Comment by DarkCat09** [comment]
Edited because of https://github.com/TxtDot/txtdot/issues/31#issuecomment-1693061637

**Comment by artegoser** [comment]
Is this going to be in the general repository?

**Comment by DarkCat09** [comment]
Didn't think about it, but yeah, we can place docs in a separate repository.

I'll start by writing Markdown files, later they can be built into a web site with MkDocs or something similar.
